### ISSUE TITLE
missing "jquery.metadata.js"

### ISSUE THREAD

**Issue by StiftungAusNachlass** [intranda/goobi-viewer-core#3]
Hi there,

i can never find the linked javascript-file:
https://github.com/intranda/goobi-viewer-core/blob/de3addafffb0abe3bc57a30215efde7826ce3b4c/goobi-viewer-core/WebContent/resources/cms/adminCmsOverview.xhtml#L34

It is neither in core or boilerplate, nor in referencetheme. Please remove it, if it isn't used anywhere or give me a hint where to find it.. :-)

Yours, Tobi

**Comment by emelpe78** [comment]
Hi Tobi,

thank you for the hint. We removed the JS-Tag from this component. It seemed to be a forgotten line of text in the big Goobi viewer universe. ;)

Cheers, Marc
