### ISSUE TITLE
userLogin.xhtml missing

### ISSUE THREAD

**Issue by StiftungAusNachlass** [intranda/goobi-viewer-core#4]
Hi,

in der layout.xhtml wird auf userLogin.xhtml verwiesen:

https://github.com/intranda/goobi-viewer-theme-boilerplate/blob/a34698081b3b5d3a5b8b94fbb69ee422da6e725c/goobi-viewer-theme-boilerplate/src/META-INF/resources/resources/themes/boilerplate/includes/layout.xhtml#L79

Die Datei finde ich nirgendwo, wo ist sie? Ich erwarte sie im Core, dort ist aber nicht...

Viele Grüße, Tobias

**Comment by emelpe78** [comment]
Hi Tobi,

da warst du etwas schnell. Dieses neue Feature ist gerade noch in der Testphase und noch nicht im master. Bitte kommentiere die Zeile in der Boilerplate solange aus. Ich werde das im Repo ergänzen.

Viele Grüße
Marc
