### ISSUE TITLE
IIIF v3 collection api have items without id

### ISSUE THREAD

**Issue by tarjelavik** [intranda/goobi-viewer-core#50]
Hi! I have noticed that the `/viewer/api/v2/collections/` REST endpoint does not create correct id for the IIIF v3 `Collection`. All collections or object manifests get this id: `https://example.org/viewer/api/v2/records/DC/manifest/`. This is not the case for the IIIF v2 collections, e.g. Goobi REST API v1.

Examples:
* https://www.digi-hub.de/viewer/api/v2/collections/DC/allgemeinerbestand/
* https://viewer.samla.no/viewer/api/v2/collections/DC/nfs.folkeminnesamlere

```json
...
"items": [
  {
    "id": "https://viewer.samla.no/viewer/api/v2/records/DC/manifest/",
    "type": "Manifest",
    "label": {
      "none": [
         "1 del av gamla bryllaupsskikkji fra Hans Hansruds folkeminnesamlinger"
      ]
    },
    "thumbnail": [
        {
        "type": "Image",
        "format": "image/jpeg",
        "id": "https://viewer.samla.no/viewer/api/v2/records/8f0015a8-2e73-4a49-9e59-e3d59f40a865/representative/full/!400,400/0/default.jpg",
        "service": [
            {
              "id": "https://viewer.samla.no/viewer/api/v2/records/8f0015a8-2e73-4a49-9e59-e3d59f40a865/representative/",
              "type": "ImageService3",
              "profile": "level2"
            }
        ]
      }
    ]
  },
  ...
]
```

Is this something that has to be configured? Or is it because of the difference in these two files?  
* [.../v2/collections/CollectionsResource](https://github.com/intranda/goobi-viewer-core/blob/17a668c1ef54615132111881af1f7f02c8c86003/goobi-viewer-core/src/main/java/io/goobi/viewer/api/rest/v2/collections/CollectionsResource.java)
* [.../v1/collections/CollectionsResource](https://github.com/intranda/goobi-viewer-core/blob/17a668c1ef54615132111881af1f7f02c8c86003/goobi-viewer-core/src/main/java/io/goobi/viewer/api/rest/v1/collections/CollectionsResource.java)

**Comment by Beechwell** [comment]
Hi @tarjelavik 

that is indeed a bug in ...v2/collections/CollectionsResource which hadn't been noticed yet. Probably because most people still use the iiif2 api. 
I've just fixed in in the develop branch. It'll probably be a while until it will be rolled out to existing instances, though.

Thanks for reporting the issue :)

Best regards,
Florian

**Comment by tarjelavik** [comment]
Thx, @Beechwell!
Will it make it to next release? 

I also note that the v2 API is slow compared to v1, but that might be connected to the erroneous implementation?

If you don't mind me asking a related question in this issue :-/. Can the collections API be configured with more metadata fields? E.g. adding fields to the IIIF metadata prop?

Could i also suggest that the manifests are valid without configuring? No viewer has complained, but the default provider logo is not a uri. It seems many institutions does not finish the configuration of Goobi before going into production.

**Comment by Beechwell** [comment]
Hi @tarjelavik 
the fix will definitely be in the next release which is probably being released in the next days. 

That the v2 API is slower than v2 probably depends on which resources are being accessed. This may depend on configuration.

The displayed metadata fields and other things can be configured in the viewer configuration file according to the documentation [here](https://docs.goobi.io/goobi-viewer-en/conf/1/33/2). Disabling some items in the configuration may also help with the performance issues you've encountered.

Best regards,
Florian

**Comment by tarjelavik** [comment]
Great! :-)
On the slowness of v2, it gathers the samme data as on v1. I guess that should not matter, but the JSON is more nested and that could be the reason.

The configuration you link to is for the actual manifest as i understand it, but i meant if the IIIF collection respons could be configured. The part is the code example in the first post above.

**Comment by tarjelavik** [comment]
Fixed :-)
