### ISSUE TITLE
Buch IDs

### ISSUE THREAD

**Issue by baerbock** [intranda/goobi-viewer-core#7]
Sehr geehrte Intranda GmbH,

wie kommt eigentlich die ID eines Scans zustande? Ist sie purer Zufall, gibt es eine Prüfziffer?

`https://haab-digital.klassik-stiftung.de/viewer/image/1370282559`

**Comment by SteffenHankiewicz** [comment]
Hallo,
Die hier zitierte ID ist strenggenommen keine ID eines Scans (also eines einzelnen Bildes) sondern die eines Werkes. Da es sich um Material einer Bibliothek handelt in diesem Fall ist es hier also genau genommen der Identifier des Bibliothekskataloges. Von dort wurde die ID während des Workflows übernommen, um eine persistente Verlinkung zwischen dem originalen (analogen) Datensatz des Katalogeintrags und dem neu angefertigten Digitalisat zu ermöglichen.

Hier mal eine Verlinkung in den Bibliothekskatalog für das zitierte Werk:
https://lhwei.gbv.de/DB=2/FKT=54/FRM=EPN%2B1370282559%2BOR%2B143587447/IMPLAND=Y/LNG=DU/LRSET=3/SET=3/SID=543f1fbb-1/SRT=YOP/TTL=1/PRS=PP%7F/NXT

Dort sieht man, dass die ID an mehreren Stellen intern verwendet wird.

Für weitere Fragen einfach melden, ok?

Viele Grüße,
Steffen
